[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://project-final-hwyo.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
